language: go

os:
  - osx

go:
  - 1.7
  - 1.8

before_install:
  brew install libusb

install:
  - go get github.com/gotmc/libusb
  - go get github.com/truveris/gousb/usb
  - go get github.com/google/gousb

script:
  - go test -v ./...
