language: go

os:
  - osx

go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"

script:
  - go test -v ./...

before_install:
  - brew upgrade libusb

install:
  - go get -v github.com/gotmc/libusb
  - go get -v github.com/google/gousb
